---
# Source: helm-check-action-sample/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-helm-check-action-sample
  labels:
    app: helm-check-action-sample
    chart: helm-check-action-sample-0.1.0
    release: test
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    app: helm-check-action-sample
    release: test
---
# Source: helm-check-action-sample/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-helm-check-action-sample
  labels:
    app: helm-check-action-sample
    chart: helm-check-action-sample-0.1.0
    release: test
    heritage: Helm
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helm-check-action-sample
        release: test
    spec:
      containers:
        - name: helm-check-action-sample
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            {}
