name: CI notify

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: "Preview Service"
    branches: main
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
