name: Preview Service22

on:
  push:
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      pr_ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).html_url }}
      pr_assignee: ${{ steps.test6.outputs.pr_assignee }}
    steps:
      - name: Get count of commits ahead of merge base
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/compare/:base...:head
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_REPOSITORY: ${{ github.repository }}
          INPUT_BASE: ${{ github.base_ref }}
          INPUT_HEAD: ${{ github.ref }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
      
      - name: test
        id: test
        run: echo "${{ github.event.issue.number }}"

      - name: test2
        id: test2
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data) }}"
      
      - name: test3
        id: test3
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).html_url }}"
        
      - name: test4
        id: test4
        run: echo "${{ steps.get_pull_request_ref.outputs.data }}"
        
      - name: test6
        id: test6
        run: echo "::set-output name=pr_assignee::${{ fromJson(steps.get_pull_request_ref.outputs.data).assignee.login }}"
      
      - name: test7
        id: test7
        run: echo "${{ steps.test6.outputs.pr_assignee }}"
      
