name: Milestone

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  slack-alert-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:pr_id
          repository: ${{ github.repository }}
          pr_id: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: vars
        id: vars
        run: echo "::set-output name=chart_location::$(echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).body }}" | grep path | awk '{print $4}')"

      - uses: actions/checkout@master

      - name: dev-values
        if: hashFiles(${{ steps.vars.outputs.chart_location }}/dev.values.yaml) != ''
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ${{ steps.vars.outputs.chart_location }}
          CHART_VALUES: ${{ steps.vars.outputs.chart_location }}/dev.values.yaml

#      - uses: actions/checkout@master
#      - name: helm-check-2
#        uses: igabaydulin/helm-check-action@0.1.4
#        env:
#          CHART_LOCATION: ${{ steps.vars.outputs.chart_location }}
#          CHART_VALUES: ${{ steps.vars.outputs.chart_location }}/test.yaml
