name: Milestone

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  get-chart-location:
    runs-on: ubuntu-latest
    outputs:
      chart_location: ${{ steps.vars.outputs.chart_location }}
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:pr_id
          repository: ${{ github.repository }}
          pr_id: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: vars
        id: vars
        run: echo "::set-output name=chart_location::$(echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).body }}" | grep path | awk '{print $4}')"

      - uses: actions/checkout@master

      - name: Check dev-values existence
        id: check_files_dev
        uses: andstor/file-existence-action@v1
        with:
          files: " ${{ steps.vars.outputs.chart_location }}/dev.values.yaml"

      - name: test6
        if: steps.check_files_dev.outputs.files_exists == 'true'
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ${{ steps.vars.outputs.chart_location }}
          CHART_VALUES: ${{ steps.vars.outputs.chart_location }}/dev.values.yaml

      - name: Check stage-values existence
        id: check_files_stage
        uses: andstor/file-existence-action@v1
        with:
          files: " ${{ steps.vars.outputs.chart_location }}/stage.values.yaml"

      - name: test7
        if: steps.check_files_stage.outputs.files_exists == 'true'
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ${{ steps.vars.outputs.chart_location }}
          CHART_VALUES: ${{ steps.vars.outputs.chart_location }}/stage.values.yaml

      - name: Check prod-values existence
        id: check_files_prod
        uses: andstor/file-existence-action@v1
        with:
          files: " ${{ steps.vars.outputs.chart_location }}/prod.values.yaml"

      - name: test8
        if: steps.check_files_prod.outputs.files_exists == 'true'
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ${{ steps.vars.outputs.chart_location }}
          CHART_VALUES: ${{ steps.vars.outputs.chart_location }}/prod.values.yamlocation.outputs.chart_location }}/prod.values.yaml)"