name: Milestone

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  slack-alert-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:pr_id
          repository: ${{ github.repository }}
          pr_id: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#       - name: get milestones ref
#         id: get_milestones_ref
#         uses: octokit/request-action@v2.x
#         with:
#           route: GET /search/issues
#           q: milestone:${{ fromJson(steps.get_pull_request_ref.outputs.data).milestone.title }}+type:pr+repo:${{ github.repository }}
#         env:
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

#       - name: milestone_full
#         id: milestone_full
#         run: echo "${{ fromJson(steps.get_milestones_ref.outputs.data) }}"

#       - name: milestone_full3
#         id: milestone_full3
#         run: echo "${{ fromJson(steps.get_milestones_ref.outputs.data).total_count }}"

#       - name: milestone_full2
#         run: echo ${{ fromJson(steps.get_milestones_ref.outputs.data).items.* }}

#       - name: milestone_full22
#         run: echo ${{ join(fromJson(steps.get_milestones_ref.outputs.data).items.*.title, ', ') }}

      - name: test2
        id: test2
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data) }}"
      
      - name: test3
        id: test3
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).html_url }}"

      - name: test7
        id: test7
        run: echo "${{ steps.get_pull_request_ref.outputs.data }}"
        
      - name: test4
        id: test4
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).body }}"

      - name: test6
        id: test6
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).body }}" | grep path

      - name: test5
        id: test5
        run: echo ::set-output name=chart_location::"${{ fromJson(steps.get_pull_request_ref.outputs.data).body }}" | grep path | awk '{print $4}'

      - name: test8
        id: test8
        run: ${{ steps.test5.outputs.chart_location }}


#      - uses: actions/checkout@master
#      - name: helm-check
#        uses: igabaydulin/helm-check-action@0.1.4
#        env:
#          CHART_LOCATION: ./helm-check-action-sample
#          CHART_VALUES: ./helm-check-action-sample/values/test.yaml

      - uses: actions/checkout@master
      - name: helm-check-2
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ${{ steps.test5.outputs.chart_location }}
          CHART_VALUES: ${{ steps.test5.outputs.chart_location }}/test.yaml
