name: Milestone

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  slack-alert-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:pr_id
          repository: ${{ github.repository }}
          pr_id: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: get milestones ref
        id: get_milestones_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /search/issues
          q: milestone:${{ fromJson(steps.get_pull_request_ref.outputs.data).milestone.title }}+type:pr+repo:${{ github.repository }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: milestone_full
        id: milestone_full
        run: echo "${{ fromJson(steps.get_milestones_ref.outputs.data) }}"

      - name: milestone_full3
        id: milestone_full3
        run: echo "${{ fromJson(steps.get_milestones_ref.outputs.data).total_count }}"

      - name: milestone_full4
        id: milestone_full4
        run: echo "${{ fromJson(steps.get_milestones_ref.outputs.data).items.*.title[0] }}"

      - name: milestone_full5
        id: milestone_full5
        run: echo "${{ fromJson(steps.get_milestones_ref.outputs.data).items.* }}"

      - name: milestone_full6
        id: milestone_full6
        run: echo "${{ fromJson(steps.get_milestones_ref.outputs.data).items[0] }}"

      - name: milestone_full7
        id: milestone_full7
        run: echo "${{ fromJson(steps.get_milestones_ref.outputs.data).items.*.url[0] }}"
