name: Preview Service

on:
  pull_request:
    types: [opened]
    branches:
      - main2

jobs:
  get-env:
    runs-on: ubuntu-latest
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/milestones/:milestone_number/labels
          repository: ${{ github.repository }}
          milestone_number: 1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: milestone_full
        id: milestone_full
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data) }}"

      - name: milestone_text
        id: milestone_text
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).*.name }}"

      - name: milestone_text1
        id: milestone_text1
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).0.name }}"


