name: Slack Alert Deploy

on:
  pull_request:
    types: [opened]
    branches:
      - main

env:
  channel: '#dev_slack_notification'

jobs:
  get-env:
    runs-on: ubuntu-latest
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}

      - name: full
        id: full
        run: echo "${{ steps.get_pull_request_ref.outputs.data }}"

      - name: full2
        id: full2
        run: echo "${{ github.event }}"

      - name: schedule
        id: schedule
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).created_at }}"

      - name: release_version
        id: release_version
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}"

      - name: milestones
        id: milestones
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).milestone.url }}"

      - name: driver
        id: driver
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).assignee.login }}"

      - name: description
        id: description
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).assignee.login }}"