name: Slack Alert Deploy

on:
  pull_request:
    types: [opened]
    branches:
      - main

env:
  channel: '#dev_slack_notification'

jobs:
  get-env:
    runs-on: ubuntu-latest
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:pr_id
          repository: ${{ github.repository }}
          pr_id: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}

      - name: full
        id: full
        run: echo "${{ steps.get_pull_request_ref.outputs.data }}"

      - name: pr_num
        id: full2
        run: echo "${{ github.event.pull_request.number }}"

      - name: schedule
        id: schedule
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).created_at }}"

      - name: release_version
        id: release_version
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}"

      - name: milestones
        id: milestones
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).milestone.url }}"

      - name: driver
        id: driver
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).assignee.login }}"

      - name: description
        id: description
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).assignee.login }}"

      - name: milestone_number
        id: milestone_number
        run: echo "${{ fromJson(steps.get_pull_request_ref.outputs.data).milestone.number }}"


      - name: get pull request ref
        id: get_pull_request_ref2
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/milestones/:milestone_number/labels
          repository: ${{ github.repository }}
          milestone_number: ${{ fromJson(steps.get_pull_request_ref.outputs.data).milestone.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: milestone_number
        id: milestone_number
        run: echo "${{ steps.get_pull_request_ref2.outputs.data }}"
