name: Log latest release
on:
  pull_request:
    types: [opened]

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - run: "echo https://github.com/jambam-cho/teset/pull/${{ github.event.number }}"
